config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  get 'welcome/index'
  devise_scope :user do
    authenticated :user do
      root :to => 'receipts#index'
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :receipts do
    resources :line_items
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :receipt

  validates_presence_of :qty, :unit_price
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :user
  has_many :line_items
  accepts_nested_attributes_for :line_items, :allow_destroy => :true, :reject_if => :reject_line_items

  def reject_line_items(attributed)
    attributed['unit_price'].blank? and attributed['qty'].blank?
  end

  validates_presence_of :date, :from_address, :to_address
  validate :date_is_date?

  has_attached_file :logo,
    styles: {
      thumb: '100x100>'
    }

  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  attr_accessor :remove_logo, :new_logo
  before_save { self.logo.clear if (remove_logo == '1' && new_logo == '0') || (remove_logo == '1' && new_logo == '1' && logo.blank?) }


  private
    def date_is_date?
      if !date.is_a?(Date)
        errors.add(:date, 'must be a valid date')
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :receipts
  has_attached_file :default_logo, styles: {
    thumb: '100x100>'
  }

  validates_attachment_content_type :default_logo, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :lockable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :omniauthable

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.provider = auth.provider
     user.uid = auth.uid
     user.email = auth.info.email
   end
  end

  def self.new_with_session(params, session)
   if data = session["devise.user_attributes"]
     new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
     end
   else
     super
   end
  end

  def password_required?
      super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  attr_accessor :remove_logo, :new_logo
  before_validation { self.default_logo.clear if (remove_logo == '1' && new_logo == '0') || (remove_logo == '1' && new_logo == '1' && default_logo.blank?) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :encrypted_password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :default_address, :default_logo, :remove_logo, :new_logo) }
      end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def index
    @line_items = LineItem.all
  end

  def show
    @line_item = LineItem.find(params[:id])
  end

  def new
    @line_item = LineItem.new
  end

  def edit
    @line_item = LineItem.find(params[:id])
  end

  def create
    @line_item = LineItem.new(params[:line_item])
  end

  def update
    @line_item = LineItem.find(params[:id])
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
  end

  private
    def line_item_params
      params.require(:line_item).permit(:quantity, :description, :unit_price, :line_total, :_destroy)
    end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @receipts = current_user.receipts.all
  end

  def show
    @receipt = current_user.receipts.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "receipt_#{@receipt.work_order_id}",
        :template => 'receipts/print.html.erb',
        :layout => 'layouts/pdf.html.erb',
        :page_size => 'Letter'
      end
    end
  end

  def new
    @receipt = current_user.receipts.build
    @line_item = @receipt.line_items.build
  end

  def create
    @receipt = current_user.receipts.build(receipt_params)

    if (@receipt.remove_logo == '0' && @receipt.new_logo == '0') || (@receipt.remove_logo == '0' && @receipt.new_logo == '1' && @receipt.logo.blank?)
      @receipt.logo = current_user.default_logo
    end

    @receipt.save

    if @receipt.save
    @line_item = @receipt.line_items.create(line_item_params)
    redirect_to @receipt
    else
    render 'new'
    end

  end

  def edit
    @receipt = current_user.receipts.find(params[:id])
    @line_item = @receipt.line_items.build
  end

  def update
    @receipt = current_user.receipts.find(params[:id])

    if @receipt.update(receipt_params)
      redirect_to @receipt
    else
      render 'edit'
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy
    redirect_to receipts_path
  end

  private
    def receipt_params
      params.require(:receipt).permit(:date, :work_order_id, :from_address, :to_address, :job_description, :subtotal, :taxes, :total, :user_id, :logo, :remove_logo, :new_logo, line_items_attributes: [:qty, :description, :unit_price, :line_total, :id, :receipt_id, :_destroy])
    end

    def line_item_params
      params.permit(:qty, :description, :unit_price, :line_total, :id, :receipt_id, :_destroy)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      user_provider = @user.provider

      case user_provider
      when "google_oauth2"
        set_flash_message(:notice, :success, :kind => "google") if is_navigational_format?
      else
        set_flash_message(:notice, :success, :kind => @user.provider) if is_navigational_format?
      end

    else
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :google_oauth2, :all
  alias_method :linkedin, :all
  alias_method :facebook, :all
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'open-uri'
  def embed_remote_image(url, content_type)
    asset = open(url, "r:UTF-8") { |f| f.read }
    base64 = Base64.encode64(asset.to_s).gsub(/\s+/, "")
    "data:#{content_type};base64,#{Rack::Utils.escape(base64)}"
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receiptmaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="menu no-print">
    <div class="menu_logo">
      <%= link_to 'Receiptmaker', root_path %>
    </div>
    <div class="no-print sign_in" data-no-turbolink>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %> &nbsp<%= link_to 'Edit Profile', edit_user_registration_path %>
        | Not you? <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
    </div>
  </div>
  <div style="margin-top:100px;"></div>
  <div class="content">
    <div class="notice no-print"><%= notice %></div>
    <div class="alert no-print"><%= alert %></div>
    <div class="clear"></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "application" %>
  </head>
  <body onload='number_pages'>
    <%= yield %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= f.fields_for :line_items do |line_item| %>
  <td class="cancelcell">
     <a class="cancel" href="javascript:;" ></a>
  </td>
  <td>
    <div class="wrapper">
      <%= line_item.text_field :qty, :class => "qty-value" %>
    </div>
  </td>
  <td>
    <div class="wrapper">
    <%= line_item.text_field :description, :class => "description" %>
    </div>
  </td>
  <td>
    <div class="wrapper">
    <%= line_item.text_field :unit_price, :class => "price-value" %>
    </div>
  </td>
  <td>
    <div class="wrapper">
    <%= line_item.text_field :line_total, :class => "linetotal" %>
    </div>
  </td>
<% end %>

app/views/line_items/_line_item.html.erb
<tr class="show_row">
  <td>
    <div class="show_wrap">
      <%= line_item.qty %>
    </div>
  </td>
  <td>
    <div class="show_wrap">
    <%= line_item.description %>
    </div>
  </td>
  <td>
    <div class="show_wrap">
    <%= line_item.unit_price %>
    </div>
  </td>
  <td>
    <div class="show_wrap">
    <%= line_item.line_total %>
    </div>
  </td>
</tr>

app/views/receipts/_form.html.erb
<%= form_for @receipt do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @receipt.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div id="form_header">
    <div id="logo" class="logo_display">
      <% if @receipt.new_record? %>
        <% if current_user.default_logo.exists? %>
          <%= image_tag current_user.default_logo.url(:original), :id => "image" %>
        <% else %>
          <img src="/images/logo.jpg" id="image" >
        <% end %>
      <% else %>
        <% if @receipt.logo.exists? %>
          <%= image_tag @receipt.logo.url(:original), :id => "image" %>
        <% else %>
          <img src="/images/logo.jpg" id="image" >
        <% end %>
      <% end %>
    </div>
    <div id="edit_form" class="logo_form" >
      <div class="edit_wrap">
        <% if @receipt.new_record? %>
          <div class="logobutton"><a id="change_logo" class="submit_button" href="javascript:;">Add Logo</a></div>
        <% else %>
        <div class="logobutton"><a id="change_logo" class="submit_button" href="javascript:;">Change Logo</a></div>
        <% end %>
        <div class="logobutton"><a id="delete_logo" class="delete_button" href="javascript:;">Remove Logo</a></div>
      </div>
    </div>
    <div id="change_form" class="logo_form">
      <div class="logobutton"><a id="change_cancel" class="cancel_button" href="javascript:;">Cancel</a></div>
      <div class="clear"></div>
      <div id="imageinput">
        <%= f.file_field :logo, :id => 'imageloc' %>
      </div>
      <div class="clear"></div>
    </div>
    <div class="delete_logo_check hidden_check"><%= f.check_box :remove_logo %></div>
    <div class="new_logo_check hidden_check"><%= f.check_box :new_logo %></div>
  </div>
  <div class="clear"></div>
  <div class="form_middle">
    <div class="entry">
      <div class="label">DATE</div>
      <% if !@receipt.new_record? %>
        <%= f.text_field :date, :value => @receipt.date.strftime("%Y-%m-%d"), :id => "datepicker" %>
      <% else %>
        <%= f.text_field :date, :id => "datepicker" %>
      <% end %>
    </div>
    <div class="entry">
      <div class="label">ORDER #</div>
      <%= f.text_field :work_order_id %>
    </div>
    <div class="clear"></div>
    <div id="address">
      <div class="entry">
        <div class="label">FROM</div>
        <% if @receipt.new_record? %>
          <%= f.text_area :from_address, :class => 'companyinfo', :rows => '6', :cols => '40', :value => current_user.default_address %>
        <% else %>
          <%= f.text_area :from_address, :class => 'companyinfo', :rows => '6', :cols => '40' %>
        <% end %>
      </div>
      <div class="entry">
        <div class="label">TO</div>
        <%= f.text_area :to_address, :class => 'companyinfo', :rows => '6', :cols => '40' %>
      </div>
    </div>
    <div class="clear"></div>
    <div id="description" class="entry">
      <div class="label">JOB DESCRIPTION</div>
      <%= f.text_area :job_description, :class => 'companyinfo', :rows => '4', :cols => '87' %>
    </div>
  </div>
  <div class="clear"></div>
  <table id="line_items">
    <%= f.fields_for :line_items do |line_item| %>
      <tr class="data-row">
        <td>
          <div class="wrapper">
            <div class="label">QUANTITY</div>
            <%= line_item.text_field :qty, :class => "qty-value" %>
          </div>
        </td>
        <td>
          <div class="wrapper">
            <div class="label">PRICE</div>
          <%= line_item.text_field :unit_price, :class => "price-value" %>
          </div>
        </td>
        <td>
          <div class="wrapper">
          <div class="label">LINE TOTAL</div>
          <%= line_item.text_field :line_total, :class => "linetotal" %>
          </div>
        </td>
        <td class="delete-cell">
          <%= line_item.hidden_field :id %>
          <%= line_item.hidden_field :_destroy, :value=> '', :class => 'destroy' %>
          <%= link_to "Delete Line Item", "#", :class=> 'delete_line_item' %>
        </td>
        <td class="desc-cell">
          <div class="wrapper">
          <div class="label">DESCRIPTION</div>
          <%= line_item.text_field :description, :class => "description" %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="add_line" >
    <%= link_to 'Add Line Item', '#', :class => 'add_line_item' %>
  </div>
  <table id="totals">
    <tr class="data-row">
      <td>
        <div class="wrapper">
          <div class="label">SUBTOTAL</div>
          <%= f.text_field :subtotal, :id => 'subtotal-value' %>
        </div>
      </td>
      <td>
        <div class="wrapper">
          <div class="label">SALES TAX</div>
          <%= f.text_field :taxes, :id => 'tax-value' %>
        </div>
      </td>
      <td>
        <div class="wrapper">
          <div class="label">TOTAL</div>
          <%= f.text_field :total, :id => 'total-value' %>
        </div>
      </td>
    </tr>
  </table>
  <% if !@receipt.new_record? %>
    <div class="delete_action">
      <%= link_to 'Delete', receipt_path(@receipt), :method => :delete, data: {:confirm => 'Are you sure?'}, :class => 'delete_button' %>
    </div>
  <% end %>
  <div class="receipt_actions">
    <%= f.submit :class => "submit_button", :id => "update_button"%>
    <% if !@receipt.new_record? %>
      <%= link_to 'Cancel', receipt_path(@receipt), :class=> "cancel_button" %>
    <% else %>
      <%= link_to 'Cancel', receipts_path, :class => "cancel_button" %>
    <% end %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h2 class="header_text">Edit Receipt</h2>
<div class="linegrey"></div>
<%= render 'form' %>

app/views/receipts/index.html.erb
<% if current_user.default_logo.exists? %>
  <div id="index_logo">
    <%= image_tag current_user.default_logo.url(:original), :id => "image" %>
  </div>
<% end %>
<div class="clear"></div>
<h2 class="header_text">Listings of All Receipts</h2>
<div class="linegrey"></div>
<div class="clear"></div>
<div class="new_button" data-no-turbolink>
  <%= link_to 'New Receipt', new_receipt_path, :class => "submit_button" %>
</div>
<table id="all_articles">
  <tr class="thead">
    <th>Date</th>
    <th>W.O.#</th>
    <th>Receipt To</th>
    <th>Total</th>
    <th></th>
    <th></th>
  </tr>
  <% @receipts.each do |receipt| %>
    <tr data-no-turbolink>
      <td><%= receipt.date.strftime("%Y-%m-%d") %></td>
      <td><%= link_to receipt.work_order_id, receipt_path(receipt) %></td>
      <td><%= receipt.to_address.lines.first %></td>
      <td><%= receipt.total %></td>
      <td><%= link_to 'View', receipt_path(receipt) %></td>
      <td><%= link_to 'Delete', receipt_path(receipt), data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/receipts/new.html.erb
<h2 class="header_text">New Receipt</h2>
<div class="linegrey"></div>
<%= render 'form' %>

app/views/receipts/print.html.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
<style type="text/css">
.content {border: none;}
 body {background: none;}
 .no-print {display: none;}
 .content {text-align: center;}
</style>
<div class="content_show">
  <div id="workorder" style="margin:0">Receipt</div>
  <div id="header">
    <div id="logo_show">
      <% if @receipt.logo.exists? %>
        <%= image_tag embed_remote_image(@receipt.logo.url(:original), 'image/png' ), :id => "image_show" %>
      <% end %>
    </div>
    <table id="meta">
      <tbody>
        <tr>
          <td class="meta-head">Date</td>
          <td><div class="textline_top"><%= @receipt.date.strftime("%b %d, %Y") %></div></td>
        </tr>
        <tr>
          <td class="meta-head">Order #</td>
          <td><div class="textline_top"><%= @receipt.work_order_id %></div></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clear"></div>
  <div id="line"></div>
  <div id="address_wrap">
    <div class="address">
      <div class="label_show" id="label-left">FROM</div>
      <div class="address_box"><%= @receipt.from_address %></div>
    </div>
    <div class="address">
      <div class="label_show">TO</div>
      <div class="address_box"><%= @receipt.to_address %></div>
    </div>
    <div class="address">
      <div class="label_show">JOB</div>
      <div class="address_box"><%= @receipt.job_description %></div>
    </div>
  </div>
  <div class="clear"></div>
  <table id="data">
    <thead>
      <tr>
        <th id="qty">Qty</th>
        <th id="description">Description</th>
        <th id="price">Unit Price</th>
        <th id="total">Line Total</th>
      </tr>
    </thead>
    <tbody>
      <%= render @receipt.line_items %>
      <script type="text/javascript">
        $('.show_row:odd').addClass("even").removeClass("odd");
        $('.show_row:even').addClass("odd").removeClass("even");
      </script>
      <tr>
        <td class="separator" colspan="4"></td>
      <tr>
      <tr class="even">
        <td id="subtotal" colspan="3">Subtotal</td>
        <td>
          <div class="wrapperbottom">
            <%= @receipt.subtotal %>
          </div>
        </td>
      </tr>
      <tr>
        <td id="taxes" colspan="3">Sales Tax</td>
        <td>
          <div class="wrapperbottom">
            <%= @receipt.taxes %>
          </div>
        </td>
      </tr>
      <tr class="even">
        <td id="finaltotal" colspan="3">Total</td>
        <td id="last_cell">
          <div class="wrapperbottom">
            <%= @receipt.total %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <div id="thankyou">Thank you for your business!</div>
  <div class="left_buttons no-print">
    <%= link_to 'Print', "javascript:print()", :class => "submit_button" %>
    <%= link_to 'Download PDF', receipt_path(@receipt, :format => :pdf), :class => "submit_button" %>

  </div>
  <div class="receipt_actions no-print" data-no-turbolink>
    <%= link_to 'Edit', edit_receipt_path(@receipt), :class => "submit_button" %>
    <%= link_to 'Close', receipts_path, :class => "cancel_button" %>
  </div>
</div>

app/views/receipts/show.html.erb
<style>
@media print {
  .content {
    border: none;
  }
  body {
    background: none;
  }
  .no-print {
    display: none;
  }
}
.content {text-align: center;}
</style>
<div class="content_show">
  <div id="workorder" style="margin:0">Receipt</div>
  <div id="header">
    <div id="logo_show">
      <% if @receipt.logo.exists? %>
        <%= image_tag @receipt.logo.url(:original), :id => "image_show" %>
      <% end %>
    </div>
    <table id="meta">
      <tbody>
        <tr>
          <td class="meta-head">Date</td>
          <td><div class="textline_top"><%= @receipt.date.strftime("%b %d, %Y") %></div></td>
        </tr>
        <tr>
          <td class="meta-head">Order #</td>
          <td><div class="textline_top"><%= @receipt.work_order_id %></div></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="clear"></div>
  <div id="line"></div>
  <div id="address_wrap">
    <div class="address">
      <div class="label_show" id="label-left">FROM</div>
      <div class="address_box"><%= @receipt.from_address %></div>
    </div>
    <div class="address">
      <div class="label_show">TO</div>
      <div class="address_box"><%= @receipt.to_address %></div>
    </div>
    <div class="address">
      <div class="label_show">JOB</div>
      <div class="address_box"><%= @receipt.job_description %></div>
    </div>
  </div>
<!--    <script type="text/javascript" >
    var heights = $(".address").map(function (){
        return $(this).height();
    }).get(),

    maxHeight = Math.max.apply(null, heights);
    $('.address').height(maxHeight);
  </script> -->
  <div class="clear"></div>
  <table id="data">
    <thead>
      <tr>
        <th id="qty">Qty</th>
        <th id="description">Description</th>
        <th id="price">Unit Price</th>
        <th id="total">Line Total</th>
      </tr>
    </thead>
    <tbody>
      <%= render @receipt.line_items %>
      <script type="text/javascript">
        $('.show_row:odd').addClass("even").removeClass("odd");
        $('.show_row:even').addClass("odd").removeClass("even");
      </script>
      <tr>
        <td class="separator" colspan="4"></td>
      <tr>
      <tr class="even">
        <td id="subtotal" colspan="3">Subtotal</td>
        <td>
          <div class="wrapperbottom">
            <%= @receipt.subtotal %>
          </div>
        </td>
      </tr>
      <tr>
        <td id="taxes" colspan="3">Sales Tax</td>
        <td>
          <div class="wrapperbottom">
            <%= @receipt.taxes %>
          </div>
        </td>
      </tr>
      <tr class="even">
        <td id="finaltotal" colspan="3">Total</td>
        <td id="last_cell">
          <div class="wrapperbottom">
            <%= @receipt.total %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <div id="thankyou">Thank you for your business!</div>
  <div class="left_buttons no-print">
    <%= link_to 'Print', "javascript:print()", :class => "submit_button" %>
    <%= link_to 'Download PDF', receipt_path(@receipt, :format => :pdf), :class => "submit_button" %>

  </div>
  <div class="receipt_actions no-print" data-no-turbolink>
    <%= link_to 'Edit', edit_receipt_path(@receipt), :class => "submit_button" %>
    <%= link_to 'Close', receipts_path, :class => "cancel_button" %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<div class="shared_links">
  <%- if controller_name != 'sessions' %>
    Already have an account? <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name), :class => "small_label" %><br />
  <% end -%>

  <div class="linegrey"></div>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end -%>

  <h3>You can also sign
    <% if controller_name != 'sessions' %>up <%end%>
    <% if controller_name != 'registrations' %>in <%end%>
    using the following providers</h3>

<!--  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end -%>
  <% end -%> -->
  <div class="social_links">
    <div class="google social_logo"><%= link_to '', "/users/auth/google_oauth2/" %></div>
    <div class="twitter social_logo"><%= link_to '', "/users/auth/twitter/" %></div>
    <div class="facebook social_logo"><%= link_to '', "/users/auth/facebook/" %></div>
    <div class="linkedin social_logo"><%= link_to '', "/users/auth/linkedin/" %></div>
  </div>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <br/>Don't have an account? <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end -%>
</div>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>